name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `plunk publish` in ...
        2. Run `plunk add ...` in ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      options:
        - npm
        - pnpm
        - yarn
        - bun
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Windows 11, macOS 15, Ubuntu 24.04
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g. 22.0.0
    validations:
      required: true
  - type: input
    id: plunk-version
    attributes:
      label: plunk version
      placeholder: e.g. 0.1.0
    validations:
      required: true
